// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// annotJSONtoListOfDataFrames
List annotJSONtoListOfDataFrames(List annot);
RcppExport SEXP emuR_annotJSONtoListOfDataFrames(SEXP annotSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type annot(annotSEXP);
    __result = Rcpp::wrap(annotJSONtoListOfDataFrames(annot));
    return __result;
END_RCPP
}
