# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

annotJSONtoListOfDataFrames <- function(annot) {
    .Call('emuR_annotJSONtoListOfDataFrames', PACKAGE = 'emuR', annot)
}

